# Valknut Comprehensive Analysis Configuration
# All features enabled by default except quality gates

# Analysis pipeline configuration
analysis:
  enable_scoring: true
  enable_graph_analysis: true
  enable_lsh_analysis: true
  enable_refactoring_analysis: true
  enable_structure_analysis: true
  enable_names_analysis: false
  enable_coverage_analysis: true
  confidence_threshold: 0.7
  max_files: 0  # 0 = unlimited
  exclude_patterns:
    - "*/node_modules/*"
    - "*/venv/*"
    - "*/target/*"
    - "*/__pycache__/*"
    - "*.min.js"
  include_patterns:
    - "**/*"

# Scoring and normalization settings
scoring:
  normalization_scheme: Standard  # Standard, z_score, min_max, robust
  use_bayesian_fallbacks: true
  confidence_reporting: true
  weights:
    complexity: 1.0
    graph: 0.8
    structure: 0.9
    style: 0.5
    refactoring: 1.2
    coverage: 0.7
  statistical_params:
    confidence_level: 0.95
    min_sample_size: 10
    outlier_threshold: 3.0

# Graph analysis configuration
graph:
  enable_betweenness: true
  enable_closeness: true
  enable_cycle_detection: true
  max_graph_size: 10000
  similarity_threshold: 0.85
  max_exact_size: 10000
  use_approximation: true
  approximation_sample_rate: 0.1

# LSH and similarity detection configuration
lsh:
  num_hashes: 128
  num_bands: 20
  shingle_size: 3
  similarity_threshold: 0.8
  max_candidates: 100
  use_semantic_similarity: false

# Structure analysis configuration
structure:
  enable_branch_packs: true
  enable_file_split_packs: true
  top_packs: 10

# Directory analysis settings
fsdir:
  max_files_per_dir: 25
  max_subdirs_per_dir: 10
  max_dir_loc: 2000
  min_branch_recommendation_gain: 0.15
  min_files_for_split: 5
  target_loc_per_subdir: 1000

# File analysis settings
fsfile:
  huge_loc: 800
  huge_bytes: 128000
  min_split_loc: 200
  min_entities_per_split: 3
  min_split_recommendation_gain: 0.20

# Partitioning configuration
partitioning:
  balance_tolerance: 0.25
  max_clusters: 4
  min_clusters: 2
  naming_fallbacks:
    - core
    - api
    - util
    - shared

# Basic naming analysis (simple pattern-based)
names:
  enabled: false
  pattern_analysis: true
  min_confidence: 0.65
  min_impact: 3
  protect_public_api: true

# Language-specific settings
languages:
  python:
    enabled: true
    file_extensions: [".py", ".pyi"]
    tree_sitter_language: "python"
    max_file_size_mb: 10.0
    complexity_threshold: 10.0
  
  javascript:
    enabled: true
    file_extensions: [".js", ".mjs", ".jsx"]
    tree_sitter_language: "javascript"
    max_file_size_mb: 5.0
    complexity_threshold: 10.0
  
  typescript:
    enabled: true
    file_extensions: [".ts", ".tsx", ".d.ts"]
    tree_sitter_language: "typescript"
    max_file_size_mb: 5.0
    complexity_threshold: 10.0
    
  rust:
    enabled: true
    file_extensions: [".rs"]
    tree_sitter_language: "rust"
    max_file_size_mb: 10.0
    complexity_threshold: 15.0
    
  go:
    enabled: true
    file_extensions: [".go"]
    tree_sitter_language: "go"
    max_file_size_mb: 8.0
    complexity_threshold: 12.0

# I/O and persistence configuration
io:
  cache_dir: null  # Uses ~/.refactor_rank/cache/ by default
  enable_caching: true
  cache_ttl_seconds: 3600  # 1 hour
  output_dir: "out"
  default_format: "json"
  report_dir: null
  report_format: "json"

# Performance and resource limits
performance:
  max_threads: null  # Use system default
  memory_limit_mb: null  # No limit
  file_timeout_seconds: 30
  total_timeout_seconds: 300
  enable_simd: true
  batch_size: 100

# Coverage analysis configuration
coverage:
  enabled: true
  report_paths:
    - "coverage.lcov"
  max_gaps_per_file: 5
  min_gap_loc: 3
  snippet_context_lines: 3
  long_gap_head_tail: 5
  group_cross_file: false
  target_repo_gain: 0.10
  weights:
    size: 0.40
    complexity: 0.20
    fan_in: 0.15
    exports: 0.10
    centrality: 0.10
    docs: 0.05
  exclude_patterns:
    - "*/tests/*"
    - "*/test/*"

# Quality gates (disabled by default - enable for CI/CD)
quality_gates:
  enabled: false
  max_complexity: 75.0
  min_health: 60.0
  max_debt: 30.0
  min_maintainability: 20.0
  max_issues: 50
  max_critical: 0
  max_high_priority: 5