# cargo-deny configuration for Valknut
# Ensures supply chain security and license compliance

[graph]
# Define the platforms we support for comprehensive dependency checking
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-apple-darwin" },
    { triple = "aarch64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "aarch64-unknown-linux-gnu" },
]
all-features = true
no-default-features = false

[output]
feature-depth = 1

[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = [
    # Add specific advisory IDs here if temporary exceptions are needed
    "RUSTSEC-2024-0320",  # yaml-rust is unmaintained but used by config crate  
    "RUSTSEC-2024-0370",  # proc-macro-error is unmaintained but used by tabled
    "RUSTSEC-2024-0436",  # paste is unmaintained but used by nalgebra/simba
]

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "BSD-2-Clause",
    "BSD-3-Clause", 
    "ISC",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "CC0-1.0",
    "Zlib",
    "MPL-2.0",
    "CDLA-Permissive-2.0",
]
# With version 2, all licenses are denied by default except those in allow list
confidence-threshold = 0.8
exceptions = [
    # Add specific crate/license combinations here if needed
    { allow = ["GPL-2.0"], name = "bloom" }, # Used for deduplication in live collectors
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"

# Skip certain crates that commonly have multiple versions
skip = [
    { name = "bitflags" },      # Many crates use different versions
    { name = "syn" },           # Proc macros often require specific versions  
    { name = "quote" },         # Paired with syn
    { name = "proc-macro2" },   # Paired with syn/quote
    { name = "indexmap" },      # Breaking changes between versions
    { name = "hashbrown" },     # Used by indexmap and std
]

skip-tree = [
    # Skip entire trees of dependencies that are known to be complex
    { name = "windows-sys" },
    { name = "winapi" },
]

deny = [
    # Deny crates with known security issues
    { name = "openssl", version = "<0.10.55" },
    # Deny unmaintained crates
    { name = "chrono", version = "<0.4.20" },
    # Prefer certain alternatives
    { name = "failure" },  # Prefer thiserror/anyhow
    { name = "error-chain" }, # Prefer thiserror
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = [
    # Allow specific git sources if needed for development versions
]