# Valknut Configuration File
# This file configures the complete valknut analysis system including
# structure analysis, semantic naming, and performance settings.

# Analysis pipeline configuration
analysis:
  enable_scoring: true
  enable_graph_analysis: true
  enable_lsh_analysis: true
  enable_refactoring_analysis: true
  enable_coverage_analysis: false
  enable_structure_analysis: true
  enable_names_analysis: true
  confidence_threshold: 0.7
  max_files: 0  # 0 = unlimited
  exclude_patterns:
    - "*/node_modules/*"
    - "*/venv/*"
    - "*/target/*"
    - "*/__pycache__/*"
    - "*.min.js"
  include_patterns:
    - "**/*"

# Semantic naming analysis configuration (using Qwen3-Embedding-0.6B)
names:
  enabled: true
  embedding_model: "Qwen/Qwen3-Embedding-0.6B-GGUF"
  min_mismatch: 0.65      # Minimum mismatch score to trigger analysis (0.0-1.0)
  min_impact: 3           # Minimum external references impact threshold
  protect_public_api: true # Protect public API functions from aggressive renaming
  abbrev_map:
    usr: user
    cfg: config
    btn: button
    mgr: manager
    svc: service
    impl: implementation
    util: utility
    calc: calculate
    auth: authentication
    admin: administrator
    proc: process
    repo: repository
    db: database
  allowed_abbrevs:
    - id
    - url
    - db
    - io
    - api
    - ui
    - os
    - fs
    - http
    - json
    - xml
    - css
    - js
    - ts
  io_libs:
    python:
      - requests
      - aiohttp
      - sqlalchemy
      - boto3
      - os
      - pathlib
      - json
      - sqlite3
      - psycopg2
      - pymongo
    typescript:
      - "node:fs"
      - fs
      - axios
      - fetch
      - pg
      - mongodb
      - sqlite3
      - redis
      - "node:http"
      - "node:https"
    rust:
      - reqwest
      - "tokio::fs"
      - sqlx
      - rusqlite
      - redis
      - mongodb
      - serde_json
      - tokio
    javascript:
      - fs
      - axios
      - fetch
      - mongodb
      - sqlite3
      - redis
      - http
      - https
    go:
      - net/http
      - database/sql
      - os
      - io/ioutil
      - encoding/json

# Structure analysis configuration
structure:
  # Directory analysis
  max_files_per_dir: 25
  max_subdirs_per_dir: 10
  max_dir_loc: 2000
  min_branch_recommendation_gain: 0.15
  
  # File analysis
  huge_loc: 800
  huge_bytes: 128000
  min_split_recommendation_gain: 0.20

# Graph analysis configuration
graph:
  enable_betweenness: true
  enable_closeness: false
  enable_cycle_detection: true
  max_exact_size: 10000
  use_approximation: true
  approximation_sample_rate: 0.1

# LSH and similarity detection configuration
lsh:
  num_hashes: 128
  num_bands: 16
  shingle_size: 3
  similarity_threshold: 0.7
  max_candidates: 100
  use_semantic_similarity: true  # Use with semantic naming analysis

# Scoring and normalization settings
scoring:
  normalization_scheme: z_score  # z_score, min_max, robust, z_score_bayesian, min_max_bayesian, robust_bayesian
  use_bayesian_fallbacks: true
  confidence_reporting: false
  weights:
    complexity: 1.0
    graph: 0.8
    structure: 0.9
    style: 0.5
    coverage: 0.7
  statistical_params:
    confidence_level: 0.95
    min_sample_size: 10
    outlier_threshold: 3.0

# Language-specific settings
languages:
  python:
    enabled: true
    file_extensions: [".py", ".pyi"]
    tree_sitter_language: "python"
    max_file_size_mb: 10.0
    complexity_threshold: 10.0
  
  javascript:
    enabled: true
    file_extensions: [".js", ".mjs", ".jsx"]
    tree_sitter_language: "javascript"
    max_file_size_mb: 5.0
    complexity_threshold: 10.0
  
  typescript:
    enabled: true
    file_extensions: [".ts", ".tsx", ".d.ts"]
    tree_sitter_language: "typescript"
    max_file_size_mb: 5.0
    complexity_threshold: 10.0
    
  rust:
    enabled: true
    file_extensions: [".rs"]
    tree_sitter_language: "rust"
    max_file_size_mb: 10.0
    complexity_threshold: 15.0

# I/O and persistence configuration
io:
  cache_dir: null  # Uses ~/.refactor_rank/cache/ by default
  enable_caching: true
  cache_ttl_seconds: 3600  # 1 hour
  report_dir: null  # Uses current directory by default
  report_format: json  # json, yaml, html, csv

# Performance and resource limits
performance:
  max_threads: null  # Use system default
  memory_limit_mb: null  # No limit
  file_timeout_seconds: 30
  total_timeout_seconds: null  # No limit
  enable_simd: true
  batch_size: 100