[2m# Default valknut configuration[0m
[2m# Save this to a file and customize as needed[0m
[2m# Usage: valknut analyze --config your-config.yml[0m

structure:
  enable_branch_packs: true
  enable_file_split_packs: true
  top_packs: 20
fsdir:
  max_files_per_dir: 25
  max_subdirs_per_dir: 10
  max_dir_loc: 2000
  min_branch_recommendation_gain: 0.15
  min_files_for_split: 5
  target_loc_per_subdir: 1000
fsfile:
  huge_loc: 800
  huge_bytes: 128000
  min_split_loc: 200
  min_entities_per_split: 3
partitioning:
  balance_tolerance: 0.25
  max_clusters: 4
  min_clusters: 2
  naming_fallbacks:
  - core
  - io
  - api
  - util

