[advisories]
# Ignore RSA vulnerability in sqlx-mysql dependency
# This is a transitive dependency through sqlx-mysql that we don't directly use
# and has no available fix. The vulnerability affects RSA PKCS#1 v1.5 decryption
# which is not used in our SQLite-focused database features.
ignore = ["RUSTSEC-2023-0071"]

# Note: Unmaintained crate warnings are noted but not blocking CI
# These are transitive dependencies:
# - paste: Used by nalgebra for mathematical computations
# - proc-macro-error: Used by tabled for CLI output formatting  
# - yaml-rust: Used by config for YAML configuration parsing