# Legacy Compatibility Configuration Example
# This configuration disables the intelligent denoising system
# to provide behavior similar to older versions

# Disable intelligent clone detection for legacy compatibility
denoise:
  enabled: false             # Disable denoising system
  auto: false               # Disable auto-calibration

# Basic analysis pipeline without intelligent features
analysis:
  enable_scoring: true
  enable_graph_analysis: true
  enable_lsh_analysis: false      # Disable LSH for basic similarity only
  enable_refactoring_analysis: true
  enable_structure_analysis: true
  confidence_threshold: 0.7

# Traditional LSH settings (when enabled)
lsh:
  num_hashes: 128
  num_bands: 16
  shingle_size: 3
  similarity_threshold: 0.7
  max_candidates: 100
  use_semantic_similarity: false

# Basic duplicate detection (legacy mode)
dedupe:
  min_function_tokens: 20        # Lower threshold for legacy compatibility
  min_match_tokens: 12           # Lower threshold for more matches
  min_match_coverage: 0.30       # Lower coverage requirement
  threshold_s: 0.70              # Lower similarity threshold
  rank_by: "similarity"          # Simple similarity ranking
  
  # Disable advanced features
  adaptive:
    auto_denoise: false
    adaptive_learning: false
    rarity_weighting: false
    structural_validation: false
    live_reach_integration: false

# Performance settings
performance:
  max_threads: null
  memory_limit_mb: null
  file_timeout_seconds: 30
  batch_size: 100