# Minimal Valknut Configuration Example
# This shows the essential settings you might want to customize
# All other settings will use intelligent defaults

# Intelligent clone detection (enabled by default)
denoise:
  enabled: true              # Enable denoising by default
  auto: true                 # Enable auto-calibration by default
  
  # Core thresholds (customize for your project)
  min_function_tokens: 40    # Minimum function size for analysis
  min_match_tokens: 24       # Minimum tokens for a meaningful match
  require_blocks: 2          # Require distinct control flow blocks
  similarity: 0.82           # Similarity threshold (0.0-1.0)

# Analysis pipeline (customize what gets analyzed)
analysis:
  enable_scoring: true
  enable_graph_analysis: true
  enable_lsh_analysis: true        # Required for clone detection
  enable_refactoring_analysis: true
  enable_structure_analysis: true
  confidence_threshold: 0.7

# Performance limits (adjust for your system)
performance:
  max_threads: null              # Use system defaults
  memory_limit_mb: null          # No memory limit
  file_timeout_seconds: 30       # Per-file timeout
  batch_size: 100               # Files processed in parallel

# Language support (enable/disable as needed)
languages:
  python:
    enabled: true
    max_file_size_mb: 10.0
  
  javascript:
    enabled: true
    max_file_size_mb: 5.0
  
  typescript:
    enabled: true
    max_file_size_mb: 5.0